# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:

      in_memory:

         memory:
            users:
                            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs

        secured_area:
           pattern: ^/
           anonymous: ~
           http_basic:
              realm: "books"

    access_control:
        - { path: ^/users, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
